{
 "title": "Services statistic",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "account_name", "query": { "query": "label_values(accountName)" } }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Payments outcome rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(payment_finished_total{service=~\"$service\"}[30s])) by (service, outcome, failReason)",
     "legendFormat": "{{outcome}} - {{failReason}}"
    }
   ]
  },
  {
   "title": "Event during testing per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(events_total{}[30s]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Income / Expenses percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
     "legendFormat": "income - {{service}}"
    },
    {
     "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
     "legendFormat": "expenses - {{service}} "
    }
   ]
  },
  {
   "title": "Income / Expenses percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
     "legendFormat": "income - {{service}}"
    },
    {
     "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
     "legendFormat": "expenses - {{service}} "
    }
   ]
  },
  {
   "title": "Income / Expenses amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "income - {{service}}"
    },
    {
     "expr": "sum(increase(external_amount_total{service=~\"$service\", accountName=~\"$account_name\"}[1m])) by (service, accountName) ",
     "legendFormat": "expenses - {{service}} - {{accountName}}"
    }
   ]
  },
  {
   "title": "Income / Expenses amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service)",
     "legendFormat": "income - {{service}}"
    },
    {
     "expr": "sum(increase(external_amount_total{service=~\"$service\", accountName=~\"$account_name\"}[$__range])) by (service, accountName) ",
     "legendFormat": "expenses - {{service}} - {{accountName}}"
    }
   ]
  },
  { "title": "Tests info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Tests run",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(test_duration_count{service=~\"$service\"}[$__range])) by (service, testOutcome)",
     "legendFormat": "{{service}} - {{testOutcome}}"
    }
   ]
  },
  {
   "title": "Success percent (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(service)(increase(test_duration_count{service=~\"$service\", testOutcome=~\"SUCCESS\"}[1m]))) / (sum by(service) (increase(test_duration_count{service=~\"$service\", testOutcome=~\".*\"}[1m])))",
     "legendFormat": "{{service}} - success"
    }
   ]
  },
  {
   "title": "Average test duration by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(test_duration_sum{service=~\"$service\"}[1m])) by (service, testOutcome) / sum by (service, testOutcome) (rate(test_duration_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - {{testOutcome}}"
    }
   ]
  },
  {
   "title": "Stages info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_ok_count{service=~\"$service\", result=\"success\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Fail stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_ok_count{service=~\"$service\", result=\"failed\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Success stages duration. Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(stage_duration_ok_sum{service=~\"$service\", result=\"success\"}[1m]) / rate(stage_duration_ok_count{service=~\"$service\", result=\"success\"}[1m])",
       "legendFormat": "{{stage}}"
      },
      {}
     ]
    }
   ]
  },
  { "title": "Http calls info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "(Clients -> Online shop) http requests processed rate (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_external_duration_count{service=~\"$service\"}[$__rate_interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "(Clients -> Online shop) http requests duration. Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_external_duration_sum{service=~\"$service\"}[1m]) / rate(http_external_duration_count{service=~\"$service\"}[1m])",
     "legendFormat": "{{method}} - {{result}}"
    }
   ]
  },
  {
   "title": "(Online shop -> Payment system)  http requests processed rate (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(external_sys_duration_count{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{accountName}} - {{outcome}}"
    }
   ]
  },
  {
   "title": "(Online shop -> Payment system)  Payment sys processing duration. Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(external_sys_duration_sum{service=~\"$service\"}[1m]) / rate(external_sys_duration_count{service=~\"$service\"}[1m])",
     "legendFormat": "{{accountName}} - {{outcome}}"
    }
   ]
  },
  {
   "title": "(Test system -> Online shop)  Average request latent time (before submit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_request_latent_sum{service=~\"$service\"}[15s]) / rate(http_request_latent_count{service=~\"$service\"}[15s])",
     "legendFormat": "{{method}} - {{result}}"
    }
   ]
  },
  {
   "title": "Executors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 573 },
     "targets": [
      {
       "expr": "max by (name) (executor_queued_tasks{service=~\"$service\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Completed tasks rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 573 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(executor_completed_tasks_total{}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Active executors threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 581 },
     "targets": [
      {
       "expr": "sum by (name) (executor_active_threads{})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage (XMX%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum ((sum by (job, area) (jvm_memory_used_bytes{area=\"heap\"}) / sum by (job, area) (jvm_memory_max_bytes{area=\"heap\"})) * 100) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "JVM threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (jvm_threads_live_threads{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (system_cpu_usage{service=~\"$service\"})",
       "legendFormat": "{{job}} - System CPU Usage"
      },
      {
       "expr": "sum by (job) (process_cpu_usage{service=~\"$service\"})",
       "legendFormat": "{{job}} -Process CPU Usage"
      }
     ]
    },
    {
     "title": "GC delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{}[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (process_files_open_files{})",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_config_max{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Thread Config Min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_config_min{service=~\"$service\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Jetty Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (job) (jetty_threads_busy{})",
       "legendFormat": "{{job}} -  busy "
      },
      {
       "expr": "sum by (job) (jetty_threads_idle{})",
       "legendFormat": "{{job}} - idle"
      },
      {
       "expr": "sum by (job) (jetty_threads_current{})",
       "legendFormat": "{{job}} - current"
      },
      {
       "expr": "sum by (job) (jetty_threads_jobs{})",
       "legendFormat": "{{job}} - jobs"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{service=~\"$service\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (job, method, status, uri) (irate(http_server_requests_seconds_sum{service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{service=~\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}} - {{job}}"
      }
     ]
    }
   ]
  },
  { "title": "Custom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Total number of payment requests received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(payment_requests_total[$__rate_interval])) by (serviceName, accountName)",
     "legendFormat": "{{serviceName}} - {{accountName}}"
    }
   ]
  },
  {
   "title": "Payment system response timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p10 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.2, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p20 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.3, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p30 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.4, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p40 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p50 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.6, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p60 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.7, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p70 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p80 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p90 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p99 - {{serviceName}} - {{accountName}}"
    }
   ]
  },
  {
   "title": "online-store rps by status and uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"online-store-job\"}[$__rate_interval])) by (status, uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment processing timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(payment_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p50 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(payment_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p75 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(payment_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p90 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(payment_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p95 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(payment_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p99 - {{serviceName}} - {{accountName}}"
    }
   ]
  },
  {
   "title": "Payment started rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(payment_started_total{accountName=~\"$account_name\", serviceName=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent in payment queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(payment_queue_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p50 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(payment_queue_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p75 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(payment_queue_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p90 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(payment_queue_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p95 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(payment_queue_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\"}[$__rate_interval])) by (serviceName, accountName, le))",
     "legendFormat": "p99 - {{serviceName}} - {{accountName}}"
    }
   ]
  },
  {
   "title": "Payment queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "payment_queue{quantile=\"0.25\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "payment_queue{quantile=\"0.5\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "payment_queue{quantile=\"0.75\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "payment_queue{quantile=\"0.9\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "payment_queue{quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "payment_queue{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Time spent in rate limiter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(payment_part_seconds_bucket{part=\"rateLimiter\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(payment_part_seconds_bucket{part=\"rateLimiter\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(payment_part_seconds_bucket{part=\"rateLimiter\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(payment_part_seconds_bucket{part=\"rateLimiter\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(payment_part_seconds_bucket{part=\"rateLimiter\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Payment responses by status and attempt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "sum(rate(payment_responses_total{accountName=~\"$account_name\", serviceName=~\"$service\"}[$__rate_interval])) by (status, attempt)",
     "legendFormat": "{{attempt}} - {{status}}"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(payment_responses_total{accountName=~\"$account_name\", serviceName=~\"$service\", status=\"error\"}[$__rate_interval])) / sum(rate(payment_responses_total{accountName=~\"$account_name\", serviceName=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{accountName}} - {{serviceName}}"
    }
   ]
  },
  {
   "title": "online-store-job endpoint rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"online-store-job\"}[$__rate_interval])) by (uri, status)",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Payment system error response timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p10 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.2, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p20 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.3, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p30 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.4, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p40 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p50 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.6, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p60 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.7, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p70 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p80 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p90 - {{serviceName}} - {{accountName}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(payment_system_processing_seconds_bucket{serviceName=~\"$service\", accountName=~\"$account_name\", status!=\"success\"}[$__rate_interval])) by (le, serviceName, accountName))",
     "legendFormat": "p99 - {{serviceName}} - {{accountName}}"
    }
   ]
  }
 ]
}